id: P002988
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25267
  title: དབུ་མ་དགོངས་རྒྱན་རིན་པོ་ཆེའི་འཕྲེང་བ།
  author: ''
  volumes:
    e0c513f6251344a587571f3330bc9d44:
      image_group_id: I1KG25269
      title: ''
      volume_number: 1
      total_pages: 436
