id: P002988
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:32:49.808153
source_metadata:
  id: bdr:W1KG25267
  title: དབུ་མ་དགོངས་རྒྱན་རིན་པོ་ཆེའི་འཕྲེང་བ།
  author: ''
  volumes:
    e0c513f6251344a587571f3330bc9d44:
      image_group_id: I1KG25269
      title: ''
      volume_number: 1
      total_pages: 436
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
